import React from 'react';
import Head from 'next/head';
import axios from 'axios';
import { Size } from '../typings/typings';

interface IForm {
  prompt: string,
  size: Size
}

export default function Home() {

  const [form, setForm] = React.useState<IForm>({
    prompt: "",
    size: Size.small
  })
  const [imageUrl, setImageUrl] = React.useState<string>("");

  const generateImage = async () => {
    const response = await axios.post("http://localhost:5000/openai/generateImage", form);
    setImageUrl(response.data.data);
  }

  const handleChange = (name: string, value: string) => {
    setForm(prev => {
      return {
        ...prev,
        [name]: value
      }
    })
  }

  return (
    <div className="bg-white w-screen min-h-screen overflow-hidden">
      <Head>
        <title>AI Image Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-dark w-full h-[20vw] shadow-xl">
        <div className="max-w-7xl mx-auto text-white flex flex-col items-center justify-center h-full">
          <h1 className="text-4xl font-bold">AI Image Generator</h1>
          <div className="flex items-center mt-12">
            <input type="text" className="rounded-lg border-4 border-white bg-slate-50 text-lg p-1 text-dark w-96" value={form.prompt} onChange={(e) => handleChange("prompt", e.target.value)} />
            <button className="ml-4 rounded-lg bg-purple text-white text-lg py-2 px-4" onClick={() => generateImage()}>Generate</button>
          </div>
          <div className="mt-8 grid grid-cols-3 text-dark">
            <button className={`px-4 py-2 ${form.size === Size.small && "bg-purple text-white"} rounded-l-lg border border-dark bg-white`} onClick={(e) => handleChange("size", Size.small)}>Small</button>
            <button className={`px-4 py-2 ${form.size === Size.medium && "bg-purple text-white"} border border-dark bg-white`} onClick={(e) => handleChange("size", Size.medium)}>Medium</button>
            <button className={`px-4 py-2 ${form.size === Size.large && "bg-purple text-white"} rounded-r-lg border border-dark bg-white`} onClick={(e) => handleChange("size", Size.large)}>Large</button>
          </div>
        </div>
      </header>

      <main className="w-screen flex items-center justify-center py-12">
        <img src={imageUrl} alt="" className="rounded-lg shadow-xl"/>
      </main>
    </div>
  )
}
